# Generated by Django 3.0.8 on 2021-02-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgurutask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='avg_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rate',
            field=models.IntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='rates_number',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
