# Generated by Django 3.0.8 on 2021-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgurutask', '0002_auto_20210222_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rates_number',
        ),
        migrations.AlterField(
            model_name='car',
            name='avg_rating',
            field=models.IntegerField(),
        ),
    ]
