# Generated by Django 3.0.8 on 2021-02-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgurutask', '0003_auto_20210222_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='avg_rating',
            field=models.IntegerField(null=True),
        ),
    ]
