# Generated by Django 3.0.8 on 2021-02-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgurutask', '0004_auto_20210222_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rates_number',
            field=models.IntegerField(null=True),
        ),
    ]
