# Generated by Django 3.0.8 on 2021-02-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netgurutask', '0007_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='netgurutask.Car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rates',
            field=models.ManyToManyField(related_name='rates', to='netgurutask.Rate'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
