# Generated by Django 3.0.8 on 2021-02-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netgurutask', '0009_auto_20210223_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rates',
        ),
    ]
