# Generated by Django 3.0.8 on 2021-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgurutask', '0010_auto_20210223_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rates',
            field=models.ManyToManyField(related_name='rates', to='netgurutask.Rate'),
        ),
    ]
