# Generated by Django 3.0.8 on 2021-02-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netgurutask', '0016_auto_20210223_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='car',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rate',
            new_name='rating',
        ),
    ]
