# Generated by Django 3.0.8 on 2021-02-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netgurutask', '0017_auto_20210223_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='make',
        ),
    ]
